# Generated by Django 5.0.7 on 2024-08-24 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('eventdate', models.DateField()),
                ('cost', models.IntegerField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
