# Generated by Django 5.0.7 on 2024-08-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_ticket_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
