# Generated by Django 5.0.7 on 2024-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='first_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
